kind: pipeline
type: ssh
name: default

clone:
  disable: true

server:
  host:
    from_secret: ssh_ip
  user: root
  password:
    from_secret: ssh_password

steps:
  - name: build
    commands:
      - cd /root/code-notes
      - git pull gogs master
      - make

trigger:
  branch:
    - master
  event:
    - push
