name: remote ssh command
on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD}}
          command: |
            cd /root/blog
            git checkout .
            git pull
            npm run build-in-docker
            